#!/bin/bash
# =============================================================
# setup.sh - ONE-TIME setup for ICT Trading Bot on Oracle Cloud
# =============================================================
# Run this once after cloning the repo on your Oracle VM.
# It will install Python dependencies and securely store
# your Bybit API keys so they persist across reboots.
#
# Usage: bash setup.sh
# =============================================================

set -e  # Exit immediately if any command fails

echo "======================================"
echo " ICT Trading Bot - Oracle Cloud Setup"
echo "======================================"
echo ""

# 1. System update and Python install
echo "[1/4] Installing system dependencies..."
sudo apt update -y
sudo apt install -y python3 python3-pip git
echo "Done."
echo ""

# 2. Install Python packages
echo "[2/4] Installing Python packages from requirements.txt..."
pip3 install --user -r requirements.txt
echo "Done."
echo ""

# 3. Prompt for API keys and save to ~/.bot_env
echo "[3/4] Setting up API keys..."
echo "Your keys will be stored in ~/.bot_env (readable only by you)."
echo "They are never written into the repo or any code file."
echo ""

read -p "Enter your Bybit API Key: " BYBIT_API_KEY
read -p "Enter your Bybit API Secret: " BYBIT_API_SECRET
read -p "Enter your Telegram Bot Token: " TELEGRAM_TOKEN
read -p "Enter your Telegram Chat ID: " TELEGRAM_CHAT_ID

# Write to ~/.bot_env
cat > "$HOME/.bot_env" << EOF
# ICT Trading Bot - Environment Variables
# Generated by setup.sh on $(date)
export BYBIT_API_KEY="$BYBIT_API_KEY"
export BYBIT_API_SECRET="$BYBIT_API_SECRET"
export TELEGRAM_TOKEN="$TELEGRAM_TOKEN"
export TELEGRAM_CHAT_ID="$TELEGRAM_CHAT_ID"
EOF

# Restrict file permissions so only the current user can read it
chmod 600 "$HOME/.bot_env"

echo "Keys saved to ~/.bot_env (chmod 600)."
echo ""

# 4. Register bot to auto-start on VM reboot via crontab
echo "[4/4] Registering bot to auto-start on reboot via cron..."
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/start.sh"
CRON_JOB="@reboot sleep 15 && bash $SCRIPT_PATH"

# Add to crontab only if not already present
( crontab -l 2>/dev/null | grep -v "start.sh"; echo "$CRON_JOB" ) | crontab -
echo "Cron job registered."
echo ""

echo "======================================"
echo " Setup complete!"
echo " Start the bot now by running:"
echo "   bash start.sh"
echo " Monitor logs with:"
echo "   tail -f bot.log"
echo "======================================"
